name: My First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:

        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Welcome
          run: |
            echo "Hello World"
            ls -ltra
            echo "This is a message from github actions workflow" >> README.md
            cat README.md

  second_job:
    runs-on: ubuntu-latest
    needs: first_job
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Create a file
          run: |
            touch Sample.txt
            ls -ltr

